# Generated by Django 5.1.6 on 2025-02-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_booking_date_buy_quantity_buy_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='order', to='app.product'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
