# Generated by Django 5.1.6 on 2025-02-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_order_buy_orderproduct_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
    ]
